Algoritmo "idadeCondicional"

Var
   ano, nasc, idade : inteiro

Inicio

      Escreva("Em que ano estamos? ")
      Leia(ano)
      Escreva("Em que ano você nasceu? ")
      Leia(nasc)
      idade <- ano - nasc
      Escreva("Em ", ano, " você terá ", idade, " anos")
      
      Se(idade >=18) entao
               Escreva(" e já terá atingido a maioridade.")
      FimSe


Fimalgoritmo

//Aula #07
//www.youtube.com/watch?v=_g05aHdBAEY&list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV&index=8