Algoritmo "operadoresRelacionais"

Var
   A, B, C : Inteiro

Inicio

      A <- 2
      B <- 3
      C <- 5

      Escreval(A > B)
      Escreval(A < B)
      Escreval(A >= B)
      Escreval(A <= B)
      Escreval(A = B)
      Escreval(A <> B)
      
      Escreval(C = A+B)
      Escreval(C >= B^A)
      Escreval(B <= C%2)
      Escreval(1 = C%2)

Fimalgoritmo

//Aula #04
//www.youtube.com/watch?v=Ig4QZNpVZYs&list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV&index=5